export const ASTRONOMICAL_OBJECTS: Record<string, { name: string; visibleInNA: boolean }> = {
    // ==================== MESSIER OBJECTS ====================
  'M1': { name: 'Messier 1 - Crab Nebula', visibleInNA: true },
  'M2': { name: 'Messier 2 - Aquarius Globular Cluster', visibleInNA: true },
  'M3': { name: 'Messier 3 - Canes Venatici Globular Cluster', visibleInNA: true },
  'M4': { name: 'Messier 4 - Scorpius Globular Cluster', visibleInNA: true },
  'M5': { name: 'Messier 5 - Serpens Globular Cluster', visibleInNA: true },
  'M6': { name: 'Messier 6 - Butterfly Cluster', visibleInNA: true },
  'M7': { name: 'Messier 7 - Ptolemy\'s Cluster', visibleInNA: true },
  'M8': { name: 'Messier 8 - Lagoon Nebula', visibleInNA: true },
  'M9': { name: 'Messier 9 - Hercules Globular Cluster', visibleInNA: true },
  'M10': { name: 'Messier 10 - Ophiuchus Globular Cluster', visibleInNA: true },
  'M11': { name: 'Messier 11 - Wild Duck Cluster', visibleInNA: true },
  'M12': { name: 'Messier 12 - Ophiuchus Globular Cluster', visibleInNA: true },
  'M13': { name: 'Messier 13 - Great Hercules Globular Cluster', visibleInNA: true },
  'M14': { name: 'Messier 14 - Ophiuchus Globular Cluster', visibleInNA: true },
  'M15': { name: 'Messier 15 - Pegasus Globular Cluster', visibleInNA: true },
  'M16': { name: 'Messier 16 - Eagle Nebula', visibleInNA: true },
  'M17': { name: 'Messier 17 - Omega Nebula', visibleInNA: true },
  'M18': { name: 'Messier 18 - Sagittarius Star Cluster', visibleInNA: true },
  'M19': { name: 'Messier 19 - Ophiuchus Globular Cluster', visibleInNA: true },
  'M20': { name: 'Messier 20 - Trifid Nebula', visibleInNA: true },
  'M21': { name: 'Messier 21 - Sagittarius Star Cluster', visibleInNA: true },
  'M22': { name: 'Messier 22 - Sagittarius Globular Cluster', visibleInNA: true },
  'M23': { name: 'Messier 23 - Sagittarius Star Cluster', visibleInNA: true },
  'M24': { name: 'Messier 24 - Sagittarius Star Cloud', visibleInNA: true },
  'M25': { name: 'Messier 25 - Sagittarius Star Cluster', visibleInNA: true },
  'M26': { name: 'Messier 26 - Scutum Star Cluster', visibleInNA: true },
  'M27': { name: 'Messier 27 - Dumbbell Nebula', visibleInNA: true },
  'M28': { name: 'Messier 28 - Sagittarius Globular Cluster', visibleInNA: true },
  'M29': { name: 'Messier 29 - Cygnus Star Cluster', visibleInNA: true },
  'M30': { name: 'Messier 30 - Capricornus Globular Cluster', visibleInNA: true },
  'M31': { name: 'Messier 31 - Andromeda Galaxy', visibleInNA: true },
  'M32': { name: 'Messier 32 - Companion to Andromeda', visibleInNA: true },
  'M33': { name: 'Messier 33 - Triangulum Galaxy', visibleInNA: true },
  'M34': { name: 'Messier 34 - Perseus Star Cluster', visibleInNA: true },
  'M35': { name: 'Messier 35 - Gemini Star Cluster', visibleInNA: true },
  'M36': { name: 'Messier 36 - Auriga Star Cluster', visibleInNA: true },
  'M37': { name: 'Messier 37 - Auriga Star Cluster', visibleInNA: true },
  'M38': { name: 'Messier 38 - Auriga Star Cluster', visibleInNA: true },
  'M39': { name: 'Messier 39 - Cygnus Star Cluster', visibleInNA: true },
  'M40': { name: 'Messier 40 - Winecke\'s Double Star', visibleInNA: true },
  'M41': { name: 'Messier 41 - Canis Major Star Cluster', visibleInNA: true },
  'M42': { name: 'Messier 42 - Orion Nebula', visibleInNA: true },
  'M43': { name: 'Messier 43 - De Mairan\'s Nebula', visibleInNA: true },
  'M44': { name: 'Messier 44 - Beehive Cluster', visibleInNA: true },
  'M45': { name: 'Messier 45 - Pleiades', visibleInNA: true },
  'M46': { name: 'Messier 46 - Puppis Star Cluster', visibleInNA: true },
  'M47': { name: 'Messier 47 - Puppis Star Cluster', visibleInNA: true },
  'M48': { name: 'Messier 48 - Hydra Star Cluster', visibleInNA: true },
  'M49': { name: 'Messier 49 - Virgo Elliptical Galaxy', visibleInNA: true },
  'M50': { name: 'Messier 50 - Monoceros Star Cluster', visibleInNA: true },
  'M51': { name: 'Messier 51 - Whirlpool Galaxy', visibleInNA: true },
  'M52': { name: 'Messier 52 - Cassiopeia Star Cluster', visibleInNA: true },
  'M53': { name: 'Messier 53 - Coma Berenices Globular Cluster', visibleInNA: true },
  'M54': { name: 'Messier 54 - Sagittarius Globular Cluster', visibleInNA: true },
  'M55': { name: 'Messier 55 - Sagittarius Globular Cluster', visibleInNA: true },
  'M56': { name: 'Messier 56 - Lyra Globular Cluster', visibleInNA: true },
  'M57': { name: 'Messier 57 - Ring Nebula', visibleInNA: true },
  'M58': { name: 'Messier 58 - Virgo Barred Spiral Galaxy', visibleInNA: true },
  'M59': { name: 'Messier 59 - Virgo Elliptical Galaxy', visibleInNA: true },
  'M60': { name: 'Messier 60 - Virgo Giant Elliptical Galaxy', visibleInNA: true },
  'M61': { name: 'Messier 61 - Virgo Spiral Galaxy', visibleInNA: true },
  'M62': { name: 'Messier 62 - Scorpius Globular Cluster', visibleInNA: true },
  'M63': { name: 'Messier 63 - Sunflower Galaxy', visibleInNA: true },
  'M64': { name: 'Messier 64 - Black Eye Galaxy', visibleInNA: true },
  'M65': { name: 'Messier 65 - Leo Triplet Galaxy', visibleInNA: true },
  'M66': { name: 'Messier 66 - Leo Triplet Galaxy', visibleInNA: true },
  'M67': { name: 'Messier 67 - Cancer Star Cluster', visibleInNA: true },
  'M68': { name: 'Messier 68 - Hydra Globular Cluster', visibleInNA: true },
  'M69': { name: 'Messier 69 - Sagittarius Globular Cluster', visibleInNA: true },
  'M70': { name: 'Messier 70 - Sagittarius Globular Cluster', visibleInNA: true },
  'M71': { name: 'Messier 71 - Sagitta Globular Cluster', visibleInNA: true },
  'M72': { name: 'Messier 72 - Aquarius Globular Cluster', visibleInNA: true },
  'M73': { name: 'Messier 73 - Aquarius Asterism', visibleInNA: true },
  'M74': { name: 'Messier 74 - Phantom Galaxy', visibleInNA: true },
  'M75': { name: 'Messier 75 - Sagittarius Globular Cluster', visibleInNA: true },
  'M76': { name: 'Messier 76 - Little Dumbbell Nebula', visibleInNA: true },
  'M77': { name: 'Messier 77 - Seyfert Galaxy', visibleInNA: true },
  'M78': { name: 'Messier 78 - Orion Reflection Nebula', visibleInNA: true },
  'M79': { name: 'Messier 79 - Lepus Globular Cluster', visibleInNA: true },
  'M80': { name: 'Messier 80 - Scorpius Globular Cluster', visibleInNA: true },
  'M81': { name: 'Messier 81 - Bode\'s Galaxy', visibleInNA: true },
  'M82': { name: 'Messier 82 - Cigar Galaxy', visibleInNA: true },
  'M83': { name: 'Messier 83 - Southern Pinwheel Galaxy', visibleInNA: true },
  'M84': { name: 'Messier 84 - Virgo Lenticular Galaxy', visibleInNA: true },
  'M85': { name: 'Messier 85 - Coma Berenices Elliptical Galaxy', visibleInNA: true },
  'M86': { name: 'Messier 86 - Virgo Elliptical Galaxy', visibleInNA: true },
  'M87': { name: 'Messier 87 - Virgo A Galaxy', visibleInNA: true },
  'M88': { name: 'Messier 88 - Coma Berenices Spiral Galaxy', visibleInNA: true },
  'M89': { name: 'Messier 89 - Virgo Elliptical Galaxy', visibleInNA: true },
  'M90': { name: 'Messier 90 - Virgo Spiral Galaxy', visibleInNA: true },
  'M91': { name: 'Messier 91 - Coma Berenices Galaxy', visibleInNA: true },
  'M92': { name: 'Messier 92 - Hercules Globular Cluster', visibleInNA: true },
  'M93': { name: 'Messier 93 - Puppis Star Cluster', visibleInNA: true },
  'M94': { name: 'Messier 94 - Croc\'s Eye Galaxy', visibleInNA: true },
  'M95': { name: 'Messier 95 - Leo Barred Spiral Galaxy', visibleInNA: true },
  'M96': { name: 'Messier 96 - Leo Spiral Galaxy', visibleInNA: true },
  'M97': { name: 'Messier 97 - Owl Nebula', visibleInNA: true },
  'M98': { name: 'Messier 98 - Coma Berenices Spiral Galaxy', visibleInNA: true },
  'M99': { name: 'Messier 99 - Coma Pinwheel Galaxy', visibleInNA: true },
  'M100': { name: 'Messier 100 - Coma Berenices Spiral Galaxy', visibleInNA: true },
  'M101': { name: 'Messier 101 - Pinwheel Galaxy', visibleInNA: true },
  'M102': { name: 'Messier 102 - Draco Spindle Galaxy', visibleInNA: true },
  'M103': { name: 'Messier 103 - Cassiopeia Star Cluster', visibleInNA: true },
  'M104': { name: 'Messier 104 - Sombrero Galaxy', visibleInNA: true },
  'M105': { name: 'Messier 105 - Leo Elliptical Galaxy', visibleInNA: true },
  'M106': { name: 'Messier 106 - Canes Venatici Spiral Galaxy', visibleInNA: true },
  'M107': { name: 'Messier 107 - Ophiuchus Globular Cluster', visibleInNA: true },
  'M108': { name: 'Messier 108 - Ursa Major Spiral Galaxy', visibleInNA: true },
  'M109': { name: 'Messier 109 - Ursa Major Barred Spiral Galaxy', visibleInNA: true },
  'M110': { name: 'Messier 110 - Companion to Andromeda', visibleInNA: true },

  // ==================== CALDWELL OBJECTS ====================
  'C1': { name: 'Caldwell 1 - Cassiopeia A Supernova Remnant', visibleInNA: true },
  'C2': { name: 'Caldwell 2 - Camelopardalis A Galaxy', visibleInNA: true },
  'C3': { name: 'Caldwell 3 - Black Eye Galaxy', visibleInNA: true },
  'C4': { name: 'Caldwell 4 - NGC 4889 Giant Elliptical Galaxy', visibleInNA: true },
  'C5': { name: 'Caldwell 5 - NGC 4559 Spiral Galaxy', visibleInNA: true },
  'C6': { name: 'Caldwell 6 - Cat\'s Eye Nebula', visibleInNA: true },
  'C7': { name: 'Caldwell 7 - NGC 2403 Spiral Galaxy', visibleInNA: true },
  'C8': { name: 'Caldwell 8 - NGC 559 Star Cluster', visibleInNA: true },
  'C9': { name: 'Caldwell 9 - Double Cluster Part A', visibleInNA: true },
  'C10': { name: 'Caldwell 10 - Double Cluster Part B', visibleInNA: true },
  'C11': { name: 'Caldwell 11 - Bubble Nebula', visibleInNA: true },
  'C12': { name: 'Caldwell 12 - Fireworks Galaxy', visibleInNA: true },
  'C13': { name: 'Caldwell 13 - Owl Cluster', visibleInNA: true },
  'C14': { name: 'Caldwell 14 - Double Cluster (Combined)', visibleInNA: true },
  'C15': { name: 'Caldwell 15 - Blinking Nebula', visibleInNA: true },
  'C16': { name: 'Caldwell 16 - NGC 7243 Star Cluster', visibleInNA: true },
  'C17': { name: 'Caldwell 17 - NGC 147 Elliptical Galaxy', visibleInNA: true },
  'C18': { name: 'Caldwell 18 - NGC 185 Elliptical Galaxy', visibleInNA: true },
  'C19': { name: 'Caldwell 19 - NGC 1491 Emission Nebula', visibleInNA: true },
  'C20': { name: 'Caldwell 20 - NGC 7331 Barred Spiral Galaxy', visibleInNA: true },
  'C21': { name: 'Caldwell 21 - NGC 1976 Orion Nebula', visibleInNA: true },
  'C22': { name: 'Caldwell 22 - Blue Planetary Nebula', visibleInNA: true },
  'C23': { name: 'Caldwell 23 - NGC 891 Edge-on Spiral Galaxy', visibleInNA: true },
  'C24': { name: 'Caldwell 24 - NGC 1275 Perseus A Galaxy', visibleInNA: true },
  'C25': { name: 'Caldwell 25 - Intergalactic Wanderer', visibleInNA: true },
  'C26': { name: 'Caldwell 26 - NGC 4244 Spiral Galaxy', visibleInNA: true },
  'C27': { name: 'Caldwell 27 - Crescent Nebula', visibleInNA: true },
  'C28': { name: 'Caldwell 28 - NGC 752 Star Cluster', visibleInNA: true },
  'C29': { name: 'Caldwell 29 - NGC 5005 Spiral Galaxy', visibleInNA: true },
  'C30': { name: 'Caldwell 30 - NGC 7331 Barred Spiral Galaxy', visibleInNA: true },
  'C31': { name: 'Caldwell 31 - NGC 405 Star Cluster', visibleInNA: true },
  'C32': { name: 'Caldwell 32 - Whale Galaxy', visibleInNA: true },
  'C33': { name: 'Caldwell 33 - Veil Nebula East', visibleInNA: true },
  'C34': { name: 'Caldwell 34 - Veil Nebula West', visibleInNA: true },
  'C35': { name: 'Caldwell 35 - NGC 4889 Elliptical Galaxy', visibleInNA: true },
  'C36': { name: 'Caldwell 36 - NGC 4559 Spiral Galaxy', visibleInNA: true },
  'C37': { name: 'Caldwell 37 - NGC 6885 Star Cluster', visibleInNA: true },
  'C38': { name: 'Caldwell 38 - Needle Galaxy', visibleInNA: true },
  'C39': { name: 'Caldwell 39 - Eskimo Nebula', visibleInNA: true },
  'C40': { name: 'Caldwell 40 - NGC 3626 Spiral Galaxy', visibleInNA: true },
  'C41': { name: 'Caldwell 41 - Hyades Star Cluster', visibleInNA: true },
  'C42': { name: 'Caldwell 42 - NGC 7006 Globular Cluster', visibleInNA: true },
  'C43': { name: 'Caldwell 43 - Little Sombrero Galaxy', visibleInNA: true },
  'C44': { name: 'Caldwell 44 - NGC 7479 Barred Spiral Galaxy', visibleInNA: true },
  'C45': { name: 'Caldwell 45 - NGC 5248 Spiral Galaxy', visibleInNA: true },
  'C46': { name: 'Caldwell 46 - NGC 5272 Messier 3 Globular Cluster', visibleInNA: true },
  'C47': { name: 'Caldwell 47 - NGC 6934 Globular Cluster', visibleInNA: true },
  'C48': { name: 'Caldwell 48 - NGC 2775 Spiral Galaxy', visibleInNA: true },
  'C49': { name: 'Caldwell 49 - Rosette Nebula', visibleInNA: true },
  'C50': { name: 'Caldwell 50 - Rosette Star Cluster', visibleInNA: true },
  'C51': { name: 'Caldwell 51 - IC 1613 Irregular Galaxy', visibleInNA: true },
  'C52': { name: 'Caldwell 52 - NGC 4697 Elliptical Galaxy', visibleInNA: true },
  'C53': { name: 'Caldwell 53 - Spindle Galaxy', visibleInNA: true },
  'C54': { name: 'Caldwell 54 - NGC 2506 Star Cluster', visibleInNA: true },
  'C55': { name: 'Caldwell 55 - Eta Carinae Nebula', visibleInNA: true },
  'C56': { name: 'Caldwell 56 - Planetary Nebula', visibleInNA: true },
  'C57': { name: 'Caldwell 57 - Barnard\'s Galaxy', visibleInNA: true },
  'C58': { name: 'Caldwell 58 - NGC 2360 Star Cluster', visibleInNA: true },
  'C59': { name: 'Caldwell 59 - NGC 3293 Star Cluster', visibleInNA: true },
  'C60': { name: 'Caldwell 60 - Antennae Galaxies', visibleInNA: true },
  'C61': { name: 'Caldwell 61 - Antennae Galaxies Companion', visibleInNA: true },
  'C62': { name: 'Caldwell 62 - NGC 247 Spiral Galaxy', visibleInNA: true },
  'C63': { name: 'Caldwell 63 - Helix Nebula', visibleInNA: true },
  'C64': { name: 'Caldwell 64 - NGC 2867 Globular Cluster', visibleInNA: true },
  'C65': { name: 'Caldwell 65 - Sculptor Galaxy', visibleInNA: true },
  'C66': { name: 'Caldwell 66 - NGC 5694 Globular Cluster', visibleInNA: true },
  'C67': { name: 'Caldwell 67 - NGC 1052 Lenticular Galaxy', visibleInNA: true },
  'C68': { name: 'Caldwell 68 - Bug Nebula', visibleInNA: true },
  'C69': { name: 'Caldwell 69 - Little Ghost Nebula', visibleInNA: true },
  'C70': { name: 'Caldwell 70 - NGC 300 Spiral Galaxy', visibleInNA: true },
  'C71': { name: 'Caldwell 71 - NGC 2477 Star Cluster', visibleInNA: true },
  'C72': { name: 'Caldwell 72 - NGC 55 Barred Spiral Galaxy', visibleInNA: true },
  'C73': { name: 'Caldwell 73 - NGC 1851 Globular Cluster', visibleInNA: true },
  'C74': { name: 'Caldwell 74 - NGC 3132 Planetary Nebula', visibleInNA: true },
  'C75': { name: 'Caldwell 75 - NGC 6124 Star Cluster', visibleInNA: true },
  'C76': { name: 'Caldwell 76 - NGC 6231 Star Cluster', visibleInNA: true },
  'C77': { name: 'Caldwell 77 - Centaurus A Galaxy', visibleInNA: true },
  'C78': { name: 'Caldwell 78 - NGC 4697 Elliptical Galaxy', visibleInNA: true },
  'C79': { name: 'Caldwell 79 - NGC 3201 Globular Cluster', visibleInNA: true },
  'C80': { name: 'Caldwell 80 - Omega Centauri Globular Cluster', visibleInNA: true },
  'C81': { name: 'Caldwell 81 - NGC 6352 Globular Cluster', visibleInNA: true },
  'C82': { name: 'Caldwell 82 - NGC 6193 Star Cluster', visibleInNA: true },
  'C83': { name: 'Caldwell 83 - NGC 4945 Spiral Galaxy', visibleInNA: true },
  'C84': { name: 'Caldwell 84 - NGC 5286 Globular Cluster', visibleInNA: true },
  'C85': { name: 'Caldwell 85 - Omicron Velorum Cluster', visibleInNA: true },
  'C86': { name: 'Caldwell 86 - NGC 6397 Globular Cluster', visibleInNA: true },
  'C87': { name: 'Caldwell 87 - NGC 1261 Globular Cluster', visibleInNA: true },
  'C88': { name: 'Caldwell 88 - NGC 5823 Star Cluster', visibleInNA: true },
  'C89': { name: 'Caldwell 89 - NGC 6541 Globular Cluster', visibleInNA: true },
  'C90': { name: 'Caldwell 90 - NGC 2867 Globular Cluster', visibleInNA: true },
  'C91': { name: 'Caldwell 91 - NGC 3201 Globular Cluster', visibleInNA: true },
  'C92': { name: 'Caldwell 92 - Eta Carinae Nebula', visibleInNA: true },
  'C93': { name: 'Caldwell 93 - NGC 6752 Globular Cluster', visibleInNA: true },
  'C94': { name: 'Caldwell 94 - Jewel Box Cluster', visibleInNA: true },
  'C95': { name: 'Caldwell 95 - NGC 6025 Star Cluster', visibleInNA: true },
  'C96': { name: 'Caldwell 96 - NGC 2808 Globular Cluster', visibleInNA: true },
  'C97': { name: 'Caldwell 97 - NGC 3766 Star Cluster', visibleInNA: true },
  'C98': { name: 'Caldwell 98 - NGC 1407 Elliptical Galaxy', visibleInNA: true },
  'C99': { name: 'Caldwell 99 - NGC 1097 Barred Spiral Galaxy', visibleInNA: true },
  'C100': { name: 'Caldwell 100 - NGC 1275 Perseus A Galaxy', visibleInNA: true },
  'C101': { name: 'Caldwell 101 - NGC 6905 Blue Planetary Nebula', visibleInNA: true },
  'C102': { name: 'Caldwell 102 - NGC 4697 Elliptical Galaxy', visibleInNA: true },
  'C103': { name: 'Caldwell 103 - NGC 2158 Star Cluster', visibleInNA: true },
  'C104': { name: 'Caldwell 104 - NGC 6171 Globular Cluster', visibleInNA: true },
  'C105': { name: 'Caldwell 105 - NGC 3195 Planetary Nebula', visibleInNA: true },
  'C106': { name: 'Caldwell 106 - 47 Tucanae Globular Cluster', visibleInNA: true },
  'C107': { name: 'Caldwell 107 - Bug Nebula', visibleInNA: true },
  'C108': { name: 'Caldwell 108 - NGC 4697 Elliptical Galaxy', visibleInNA: true },
  'C109': { name: 'Caldwell 109 - NGC 3995 Galaxy', visibleInNA: true },
  'C110': { name: 'Caldwell 110 - NGC 1851 Globular Cluster', visibleInNA: true },

  // ==================== NGC OBJECTS ====================
  'NGC253': { name: 'NGC 253 - Sculptor Galaxy', visibleInNA: true },
  'NGC300': { name: 'NGC 300 - Sculptor Spiral Galaxy', visibleInNA: true },
  'NGC457': { name: 'NGC 457 - Owl Cluster', visibleInNA: true },
  'NGC598': { name: 'NGC 598 - Triangulum Galaxy', visibleInNA: true },
  'NGC869': { name: 'NGC 869 - Double Cluster Part A', visibleInNA: true },
  'NGC884': { name: 'NGC 884 - Double Cluster Part B', visibleInNA: true },
  'NGC1023': { name: 'NGC 1023 - Lenticular Galaxy', visibleInNA: true },
  'NGC1052': { name: 'NGC 1052 - Lenticular Galaxy', visibleInNA: true },
  'NGC1097': { name: 'NGC 1097 - Barred Spiral Galaxy', visibleInNA: true },
  'NGC1232': { name: 'NGC 1232 - Spiral Galaxy', visibleInNA: true },
  'NGC1275': { name: 'NGC 1275 - Perseus A Galaxy', visibleInNA: true },
  'NGC1300': { name: 'NGC 1300 - Barred Spiral Galaxy', visibleInNA: true },
  'NGC1302': { name: 'NGC 1302 - Elliptical Galaxy', visibleInNA: true },
  'NGC1316': { name: 'NGC 1316 - Fornax A Galaxy', visibleInNA: true },
  'NGC1365': { name: 'NGC 1365 - Great Barred Spiral Galaxy', visibleInNA: true },
  'NGC1407': { name: 'NGC 1407 - Elliptical Galaxy', visibleInNA: true },
  'NGC1512': { name: 'NGC 1512 - Ring Galaxy', visibleInNA: true },
  'NGC1530': { name: 'NGC 1530 - Barred Spiral Galaxy', visibleInNA: true },
  'NGC1555': { name: 'NGC 1555 - Hind\'s Variable Nebula', visibleInNA: true },
  'NGC1566': { name: 'NGC 1566 - Spiral Galaxy', visibleInNA: true },
  'NGC1672': { name: 'NGC 1672 - Barred Spiral Galaxy', visibleInNA: true },
  'NGC1976': { name: 'NGC 1976 - Orion Nebula Region', visibleInNA: true },
  'NGC1977': { name: 'NGC 1977 - Running Man Nebula', visibleInNA: true },
  'NGC2024': { name: 'NGC 2024 - Flame Nebula', visibleInNA: true },
  'NGC2068': { name: 'NGC 2068 - Orion B Nebula', visibleInNA: true },
  'NGC2074': { name: 'NGC 2074 - Open Cluster in Orion', visibleInNA: true },
  'NGC2169': { name: 'NGC 2169 - Open Cluster', visibleInNA: true },
  'NGC2244': { name: 'NGC 2244 - Rosette Star Cluster', visibleInNA: true },
  'NGC2264': { name: 'NGC 2264 - Cone Nebula / Christmas Tree Cluster', visibleInNA: true },
  'NGC2346': { name: 'NGC 2346 - Butterfly Nebula', visibleInNA: true },
  'NGC2392': { name: 'NGC 2392 - Eskimo Nebula', visibleInNA: true },
  'NGC2403': { name: 'NGC 2403 - Spiral Galaxy', visibleInNA: true },
  'NGC2440': { name: 'NGC 2440 - Planetary Nebula', visibleInNA: true },
  'NGC2632': { name: 'NGC 2632 - Beehive Cluster', visibleInNA: true },
  'NGC2682': { name: 'NGC 2682 - Messier 67 Star Cluster', visibleInNA: true },
  'NGC2683': { name: 'NGC 2683 - Spiral Galaxy', visibleInNA: true },
  'NGC2841': { name: 'NGC 2841 - Spiral Galaxy', visibleInNA: true },
  'NGC2903': { name: 'NGC 2903 - Barred Spiral Galaxy', visibleInNA: true },
  'NGC3031': { name: 'NGC 3031 - Messier 81 Galaxy', visibleInNA: true },
  'NGC3034': { name: 'NGC 3034 - Messier 82 Galaxy', visibleInNA: true },
  'NGC3115': { name: 'NGC 3115 - Spindle Galaxy', visibleInNA: true },
  'NGC3201': { name: 'NGC 3201 - Globular Cluster', visibleInNA: true },
  'NGC3227': { name: 'NGC 3227 - Spiral Galaxy', visibleInNA: true },
  'NGC3242': { name: 'NGC 3242 - Ghost of Jupiter Nebula', visibleInNA: true },
  'NGC3379': { name: 'NGC 3379 - Messier 105 Galaxy', visibleInNA: true },
  'NGC3384': { name: 'NGC 3384 - Elliptical Galaxy', visibleInNA: true },
  'NGC3521': { name: 'NGC 3521 - Spiral Galaxy', visibleInNA: true },
  'NGC3627': { name: 'NGC 3627 - Messier 66 Galaxy', visibleInNA: true },
  'NGC3628': { name: 'NGC 3628 - Hamburger Galaxy', visibleInNA: true },
  'NGC3842': { name: 'NGC 3842 - Elliptical Galaxy', visibleInNA: true },
  'NGC4038': { name: 'NGC 4038 - Antennae Galaxies', visibleInNA: true },
  'NGC4039': { name: 'NGC 4039 - Antennae Companion Galaxy', visibleInNA: true },
  'NGC4151': { name: 'NGC 4151 - Seyfert Galaxy', visibleInNA: true },
  'NGC4242': { name: 'NGC 4242 - Caldwell Galaxy', visibleInNA: true },
  'NGC4244': { name: 'NGC 4244 - Silver Sliver Galaxy', visibleInNA: true },
  'NGC4261': { name: 'NGC 4261 - Elliptical Galaxy', visibleInNA: true },
  'NGC4273': { name: 'NGC 4273 - Seyfert Galaxy', visibleInNA: true },
  'NGC4278': { name: 'NGC 4278 - Elliptical Galaxy', visibleInNA: true },
  'NGC4314': { name: 'NGC 4314 - Barred Spiral Galaxy', visibleInNA: true },
  'NGC4321': { name: 'NGC 4321 - Messier 100 Galaxy', visibleInNA: true },
  'NGC4374': { name: 'NGC 4374 - Messier 84 Galaxy', visibleInNA: true },
  'NGC4382': { name: 'NGC 4382 - Messier 85 Galaxy', visibleInNA: true },
  'NGC4406': { name: 'NGC 4406 - Messier 86 Galaxy', visibleInNA: true },
  'NGC4472': { name: 'NGC 4472 - Messier 49 Galaxy', visibleInNA: true },
  'NGC4486': { name: 'NGC 4486 - Messier 87 Galaxy', visibleInNA: true },
  'NGC4494': { name: 'NGC 4494 - Elliptical Galaxy', visibleInNA: true },
  'NGC4535': { name: 'NGC 4535 - Virgo Galaxy', visibleInNA: true },
  'NGC4552': { name: 'NGC 4552 - Messier 89 Galaxy', visibleInNA: true },
  'NGC4564': { name: 'NGC 4564 - Elliptical Galaxy', visibleInNA: true },
  'NGC4621': { name: 'NGC 4621 - Messier 59 Galaxy', visibleInNA: true },
  'NGC4636': { name: 'NGC 4636 - Elliptical Galaxy', visibleInNA: true },
  'NGC4649': { name: 'NGC 4649 - Messier 60 Galaxy', visibleInNA: true },
  'NGC4826': { name: 'NGC 4826 - Black Eye Galaxy', visibleInNA: true },
  'NGC5053': { name: 'NGC 5053 - Globular Cluster', visibleInNA: true },
  'NGC5055': { name: 'NGC 5055 - Messier 63 Galaxy', visibleInNA: true },
  'NGC5194': { name: 'NGC 5194 - Messier 51 Whirlpool Galaxy', visibleInNA: true },
  'NGC5195': { name: 'NGC 5195 - Messier 51 Companion', visibleInNA: true },
  'NGC5272': { name: 'NGC 5272 - Messier 3 Globular Cluster', visibleInNA: true },
  'NGC5457': { name: 'NGC 5457 - Messier 101 Pinwheel Galaxy', visibleInNA: true },
  'NGC5585': { name: 'NGC 5585 - Spiral Galaxy', visibleInNA: true },
  'NGC5676': { name: 'NGC 5676 - Spiral Galaxy', visibleInNA: true },
  'NGC5746': { name: 'NGC 5746 - Spiral Galaxy', visibleInNA: true },
  'NGC5866': { name: 'NGC 5866 - Messier 102 Galaxy', visibleInNA: true },
  'NGC5907': { name: 'NGC 5907 - Knife Edge Galaxy', visibleInNA: true },
  'NGC5921': { name: 'NGC 5921 - Spiral Galaxy', visibleInNA: true },
  'NGC6090': { name: 'NGC 6090 - Interacting Galaxies', visibleInNA: true },
  'NGC6205': { name: 'NGC 6205 - Messier 13 Globular Cluster', visibleInNA: true },
  'NGC6207': { name: 'NGC 6207 - Spiral Galaxy', visibleInNA: true },
  'NGC6210': { name: 'NGC 6210 - Turtle Nebula', visibleInNA: true },
  'NGC6218': { name: 'NGC 6218 - Messier 12 Globular Cluster', visibleInNA: true },
  'NGC6229': { name: 'NGC 6229 - Globular Cluster', visibleInNA: true },
  'NGC6235': { name: 'NGC 6235 - Globular Cluster', visibleInNA: true },
  'NGC6254': { name: 'NGC 6254 - Messier 10 Globular Cluster', visibleInNA: true },
  'NGC6266': { name: 'NGC 6266 - Messier 62 Globular Cluster', visibleInNA: true },
  'NGC6273': { name: 'NGC 6273 - Messier 19 Globular Cluster', visibleInNA: true },
  'NGC6284': { name: 'NGC 6284 - Globular Cluster', visibleInNA: true },
  'NGC6287': { name: 'NGC 6287 - Globular Cluster', visibleInNA: true },
  'NGC6293': { name: 'NGC 6293 - Globular Cluster', visibleInNA: true },
  'NGC6302': { name: 'NGC 6302 - Bug Nebula', visibleInNA: true },
  'NGC6304': { name: 'NGC 6304 - Globular Cluster', visibleInNA: true },
  'NGC6309': { name: 'NGC 6309 - Box Nebula', visibleInNA: true },
  'NGC6316': { name: 'NGC 6316 - Globular Cluster', visibleInNA: true },
  'NGC6319': { name: 'NGC 6319 - Planetary Nebula', visibleInNA: true },
  'NGC6326': { name: 'NGC 6326 - Planetary Nebula', visibleInNA: true },
  'NGC6333': { name: 'NGC 6333 - Messier 9 Globular Cluster', visibleInNA: true },
  'NGC6338': { name: 'NGC 6338 - Globular Cluster', visibleInNA: true },
  'NGC6341': { name: 'NGC 6341 - Messier 92 Globular Cluster', visibleInNA: true },
  'NGC6356': { name: 'NGC 6356 - Globular Cluster', visibleInNA: true },
  'NGC6369': { name: 'NGC 6369 - Little Ghost Nebula', visibleInNA: true },
  'NGC6379': { name: 'NGC 6379 - Globular Cluster', visibleInNA: true },
  'NGC6402': { name: 'NGC 6402 - Messier 14 Globular Cluster', visibleInNA: true },
  'NGC6426': { name: 'NGC 6426 - Globular Cluster', visibleInNA: true },
  'NGC6440': { name: 'NGC 6440 - Globular Cluster', visibleInNA: true },
  'NGC6441': { name: 'NGC 6441 - Globular Cluster', visibleInNA: true },
  'NGC6445': { name: 'NGC 6445 - Little Gem Nebula', visibleInNA: true },
  'NGC6453': { name: 'NGC 6453 - Globular Cluster', visibleInNA: true },
  'NGC6528': { name: 'NGC 6528 - Globular Cluster', visibleInNA: true },
  'NGC6537': { name: 'NGC 6537 - Red Spider Nebula', visibleInNA: true },
  'NGC6543': { name: 'NGC 6543 - Cat\'s Eye Nebula', visibleInNA: true },
  'NGC6544': { name: 'NGC 6544 - Globular Cluster', visibleInNA: true },
  'NGC6553': { name: 'NGC 6553 - Globular Cluster', visibleInNA: true },
  'NGC6572': { name: 'NGC 6572 - Blue Planetary Nebula', visibleInNA: true },
  'NGC6578': { name: 'NGC 6578 - Planetary Nebula', visibleInNA: true },
  'NGC6589': { name: 'NGC 6589 - Open Cluster', visibleInNA: true },
  'NGC6604': { name: 'NGC 6604 - Open Cluster', visibleInNA: true },
  'NGC6611': { name: 'NGC 6611 - Messier 16 Eagle Nebula', visibleInNA: true },
  'NGC6618': { name: 'NGC 6618 - Messier 17 Omega Nebula', visibleInNA: true },
  'NGC6626': { name: 'NGC 6626 - Messier 28 Globular Cluster', visibleInNA: true },
  'NGC6637': { name: 'NGC 6637 - Messier 69 Globular Cluster', visibleInNA: true },
  'NGC6638': { name: 'NGC 6638 - Globular Cluster', visibleInNA: true },
  'NGC6642': { name: 'NGC 6642 - Globular Cluster', visibleInNA: true },
  'NGC6652': { name: 'NGC 6652 - Globular Cluster', visibleInNA: true },
  'NGC6656': { name: 'NGC 6656 - Messier 22 Globular Cluster', visibleInNA: true },
  'NGC6681': { name: 'NGC 6681 - Messier 70 Globular Cluster', visibleInNA: true },
  'NGC6694': { name: 'NGC 6694 - Messier 26 Open Cluster', visibleInNA: true },
  'NGC6705': { name: 'NGC 6705 - Messier 11 Wild Duck Cluster', visibleInNA: true },
  'NGC6709': { name: 'NGC 6709 - Open Cluster', visibleInNA: true },
  'NGC6720': { name: 'NGC 6720 - Messier 57 Ring Nebula', visibleInNA: true },
  'NGC6729': { name: 'NGC 6729 - R Coronae Australis Nebula', visibleInNA: true },
  'NGC6752': { name: 'NGC 6752 - Globular Cluster', visibleInNA: true },
  'NGC6760': { name: 'NGC 6760 - Globular Cluster', visibleInNA: true },
  'NGC6779': { name: 'NGC 6779 - Messier 56 Globular Cluster', visibleInNA: true },
  'NGC6781': { name: 'NGC 6781 - Planetary Nebula', visibleInNA: true },
  'NGC6802': { name: 'NGC 6802 - Open Cluster', visibleInNA: true },
  'NGC6818': { name: 'NGC 6818 - Little Gem Nebula', visibleInNA: true },
  'NGC6826': { name: 'NGC 6826 - Blinking Nebula', visibleInNA: true },
  'NGC6834': { name: 'NGC 6834 - Open Cluster', visibleInNA: true },
  'NGC6842': { name: 'NGC 6842 - Planetary Nebula', visibleInNA: true },
  'NGC6853': { name: 'NGC 6853 - Messier 27 Dumbbell Nebula', visibleInNA: true },
  'NGC6866': { name: 'NGC 6866 - Open Cluster', visibleInNA: true },
  'NGC6883': { name: 'NGC 6883 - Open Cluster', visibleInNA: true },
  'NGC6888': { name: 'NGC 6888 - Crescent Nebula', visibleInNA: true },
  'NGC6891': { name: 'NGC 6891 - Planetary Nebula', visibleInNA: true },
  'NGC6905': { name: 'NGC 6905 - Blue Planetary Nebula', visibleInNA: true },
  'NGC6913': { name: 'NGC 6913 - Messier 29 Open Cluster', visibleInNA: true },
  'NGC6946': { name: 'NGC 6946 - Fireworks Galaxy', visibleInNA: true },
  'NGC6960': { name: 'NGC 6960 - Veil Nebula West', visibleInNA: true },
  'NGC6992': { name: 'NGC 6992 - Veil Nebula East', visibleInNA: true },
  'NGC7000': { name: 'NGC 7000 - North America Nebula', visibleInNA: true },
  'NGC7008': { name: 'NGC 7008 - Fetus Nebula', visibleInNA: true },
  'NGC7027': { name: 'NGC 7027 - Compact Planetary Nebula', visibleInNA: true },
  'NGC7048': { name: 'NGC 7048 - Planetary Nebula', visibleInNA: true },
  'NGC7078': { name: 'NGC 7078 - Messier 15 Globular Cluster', visibleInNA: true },
  'NGC7089': { name: 'NGC 7089 - Messier 2 Globular Cluster', visibleInNA: true },
  'NGC7099': { name: 'NGC 7099 - Messier 30 Globular Cluster', visibleInNA: true },
  'NGC7129': { name: 'NGC 7129 - Open Cluster with Nebula', visibleInNA: true },
  'NGC7142': { name: 'NGC 7142 - Open Cluster', visibleInNA: true },
  'NGC7160': { name: 'NGC 7160 - Open Cluster', visibleInNA: true },
  'NGC7209': { name: 'NGC 7209 - Open Cluster', visibleInNA: true },
  'NGC7226': { name: 'NGC 7226 - Open Cluster', visibleInNA: true },
  'NGC7235': { name: 'NGC 7235 - Open Cluster', visibleInNA: true },
  'NGC7243': { name: 'NGC 7243 - Open Cluster', visibleInNA: true },
  'NGC7331': { name: 'NGC 7331 - Barred Spiral Galaxy', visibleInNA: true },
  'NGC7380': { name: 'NGC 7380 - Wizard Nebula', visibleInNA: true },
  'NGC7392': { name: 'NGC 7392 - Open Cluster', visibleInNA: true },
  'NGC7419': { name: 'NGC 7419 - Open Cluster', visibleInNA: true },
  'NGC7492': { name: 'NGC 7492 - Globular Cluster', visibleInNA: true },
  'NGC7510': { name: 'NGC 7510 - Open Cluster', visibleInNA: true },
  'NGC7662': { name: 'NGC 7662 - Blue Snowball Nebula', visibleInNA: true },

  // ==================== IC OBJECTS ====================
  'IC348': { name: 'IC 348 - Nebula in Perseus', visibleInNA: true },
  'IC405': { name: 'IC 405 - Flaming Star Nebula', visibleInNA: true },
  'IC410': { name: 'IC 410 - Tadpole Nebula', visibleInNA: true },
  'IC434': { name: 'IC 434 - Horsehead Nebula Region', visibleInNA: true },
  'IC443': { name: 'IC 443 - Jellyfish Nebula', visibleInNA: true },
  'IC1275': { name: 'IC 1275 - Planetary Nebula', visibleInNA: true },
  'IC1396': { name: 'IC 1396 - Emission Nebula', visibleInNA: true },
  'IC1613': { name: 'IC 1613 - Irregular Galaxy', visibleInNA: true },
  'IC2118': { name: 'IC 2118 - Witch Head Nebula', visibleInNA: true },
  'IC2602': { name: 'IC 2602 - Theta Carinae Cluster', visibleInNA: true },
  'IC4499': { name: 'IC 4499 - Globular Cluster', visibleInNA: true },
  'IC5070': { name: 'IC 5070 - Pelican Nebula', visibleInNA: true },
  'IC5076': { name: 'IC 5076 - Emission Nebula', visibleInNA: true },
  'IC5146': { name: 'IC 5146 - Cocoon Nebula', visibleInNA: true },
  'IC5200': { name: 'IC 5200 - Open Cluster', visibleInNA: true },

};
